<a href="https://colab.research.google.com/github/Mun-Robbery/Mun-Robbery/blob/main/autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import torch

x = torch.randn(3, requires_grad=True)
x

tensor([-0.1495,  0.0077,  1.5175], requires_grad=True)

In [28]:
y = x + 2
y

tensor([1.8505, 2.0077, 3.5175], grad_fn=<AddBackward0>)

In [29]:
z = y * y * 2
z

tensor([ 6.8488,  8.0615, 24.7460], grad_fn=<MulBackward0>)

In [31]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)

In [32]:
z.backward(v) # dz/dx
print(x.grad)

tensor([0.7402, 8.0307, 0.0141])


In [34]:
# grad changing
x = torch.randn(3, requires_grad=True)
print(x)
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():
x.requires_grad_(False)
x

tensor([ 0.4066,  0.1178, -1.2000], requires_grad=True)


tensor([ 0.4066,  0.1178, -1.2000])

In [35]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x.detach()
y

tensor([0.4407, 0.7150, 0.3575], requires_grad=True)


tensor([0.4407, 0.7150, 0.3575])

In [37]:
with torch.no_grad():
  y = x + 2
  print(y)

tensor([2.4407, 2.7150, 2.3575])


In [42]:
# dummy model
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights * 3).sum()

  model_output.backward()

  print(weights.grad)
  weights.grad.zero_()


tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights, lr=0.01)
torch.optim.step()
optimizer.zero_grad()