<a href="https://colab.research.google.com/github/Mun-Robbery/Mun-Robbery/blob/main/dataset_and_dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

epoch - 1 forward and backward pass of all training samples
<p>
batch_size - number of training samples in one forward & backward pass
<p>
number of iterations = number os passes, each pass using [batch_size] number of samples
<p>
e.g. 100 samples, batch_size = 20 => 100/20 = 5 iterations for 1 epoch


In [2]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [28]:
class WineDataset(Dataset):
  def __init__(self):
    # data loading
    xy = np.loadtxt('/content/wine.csv', delimiter=',', dtype=np.float32, skiprows=1)
    self.x = torch.from_numpy(xy[:, 1:])
    self.y = torch.from_numpy(xy[:, 0]) # n_samples, 1
    self.n_samples = xy.shape[0]
  def __getitem__(self, index):
    # dataset[0]
    return self.x[index], self.y[index]
  def __len__(self):
    return self.n_samples

In [29]:
dataset = WineDataset()
fierst_data = dataset[0]
features, labels = fierst_data
features, labels

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03]),
 tensor(1.))

In [33]:
dataloader = DataLoader(dataset=dataset, batch_size=4, shuffle=True, num_workers=2)
dataiter = iter(dataloader)
data = next(dataiter)
features, labels = data
features, labels

(tensor([[1.3830e+01, 1.6500e+00, 2.6000e+00, 1.7200e+01, 9.4000e+01, 2.4500e+00,
          2.9900e+00, 2.2000e-01, 2.2900e+00, 5.6000e+00, 1.2400e+00, 3.3700e+00,
          1.2650e+03],
         [1.3880e+01, 1.8900e+00, 2.5900e+00, 1.5000e+01, 1.0100e+02, 3.2500e+00,
          3.5600e+00, 1.7000e-01, 1.7000e+00, 5.4300e+00, 8.8000e-01, 3.5600e+00,
          1.0950e+03],
         [1.4060e+01, 2.1500e+00, 2.6100e+00, 1.7600e+01, 1.2100e+02, 2.6000e+00,
          2.5100e+00, 3.1000e-01, 1.2500e+00, 5.0500e+00, 1.0600e+00, 3.5800e+00,
          1.2950e+03],
         [1.2700e+01, 3.5500e+00, 2.3600e+00, 2.1500e+01, 1.0600e+02, 1.7000e+00,
          1.2000e+00, 1.7000e-01, 8.4000e-01, 5.0000e+00, 7.8000e-01, 1.2900e+00,
          6.0000e+02]]),
 tensor([1., 1., 1., 3.]))

In [34]:
# tarining loop
num_epoch = 2
total_samples = len(dataset)
n_iters = math.ceil(total_samples/4)
total_samples, n_iters

(178, 45)

In [35]:
for epoch in range(num_epoch):
  for i, (inputs, labels) in enumerate(dataloader):
    # forward backward, update
    if (i+1) % 5 ==0:
      print(f'epoch {epoch+1}/{num_epoch}, steps {i+1}/{n_iters}, inputs {inputs.shape}')

epoch 1/2, steps 5/45, inputs torch.Size([4, 13])
epoch 1/2, steps 10/45, inputs torch.Size([4, 13])
epoch 1/2, steps 15/45, inputs torch.Size([4, 13])
epoch 1/2, steps 20/45, inputs torch.Size([4, 13])
epoch 1/2, steps 25/45, inputs torch.Size([4, 13])
epoch 1/2, steps 30/45, inputs torch.Size([4, 13])
epoch 1/2, steps 35/45, inputs torch.Size([4, 13])
epoch 1/2, steps 40/45, inputs torch.Size([4, 13])
epoch 1/2, steps 45/45, inputs torch.Size([2, 13])
epoch 2/2, steps 5/45, inputs torch.Size([4, 13])
epoch 2/2, steps 10/45, inputs torch.Size([4, 13])
epoch 2/2, steps 15/45, inputs torch.Size([4, 13])
epoch 2/2, steps 20/45, inputs torch.Size([4, 13])
epoch 2/2, steps 25/45, inputs torch.Size([4, 13])
epoch 2/2, steps 30/45, inputs torch.Size([4, 13])
epoch 2/2, steps 35/45, inputs torch.Size([4, 13])
epoch 2/2, steps 40/45, inputs torch.Size([4, 13])
epoch 2/2, steps 45/45, inputs torch.Size([2, 13])


In [ ]:
torchvision.darasets.MNIST()
# fashion-mnist, cifar, coca