<a href="https://colab.research.google.com/github/Mun-Robbery/Mun-Robbery/blob/main/tensor_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch

x = torch.empty(3, 2, 3)
x

tensor([[[-7.6042e-27,  4.5183e-41, -7.6042e-27],
         [ 4.5183e-41,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 3.1361e-41,  1.8788e+31,  1.7220e+22]],

        [[ 2.1715e-18,  1.7395e-04,  4.2467e-08],
         [ 5.2002e+22,  2.7061e+23,  3.3063e-09]]])


In [7]:
x = torch.rand(2, 2)
x

tensor([[0.1441, 0.3001],
        [0.4082, 0.9747]])

In [12]:
x = torch.zeros(2, 2, dtype=torch.float16) # torcg.ones()
x

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float16)

In [13]:
x.size()

torch.Size([2, 2])

In [15]:
x = torch.tensor([2.5, 0.1])
x

tensor([2.5000, 0.1000])

In [17]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
z = x + y
print(z)

tensor([[0.1160, 0.3318],
        [0.3310, 0.8755]])
tensor([[0.3515, 0.9601],
        [0.1673, 0.6483]])
tensor([[0.4675, 1.2919],
        [0.4983, 1.5238]])


In [18]:
# inplace adfition
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.8080, 0.5635],
        [0.2753, 0.9711]])
tensor([[0.7418, 0.7089],
        [0.0617, 0.5306]])
tensor([[1.5498, 1.2725],
        [0.3370, 1.5017]])


In [20]:
x = torch.rand(5, 3)
print(x)
print(x[:, 0])


tensor([[0.1193, 0.4966, 0.9454],
        [0.6033, 0.3737, 0.9804],
        [0.6309, 0.3482, 0.3515],
        [0.8989, 0.1154, 0.5858],
        [0.3434, 0.8727, 0.2613]])
tensor([0.1193, 0.6033, 0.6309, 0.8989, 0.3434])


In [21]:
# reshape

x = torch.rand(4, 4)
print(x)
y = x.view(16)
print(y)

tensor([[0.4741, 0.7903, 0.6451, 0.0182],
        [0.3200, 0.0618, 0.6729, 0.2439],
        [0.3694, 0.1325, 0.7792, 0.5392],
        [0.1350, 0.3100, 0.5018, 0.8722]])
tensor([0.4741, 0.7903, 0.6451, 0.0182, 0.3200, 0.0618, 0.6729, 0.2439, 0.3694,
        0.1325, 0.7792, 0.5392, 0.1350, 0.3100, 0.5018, 0.8722])


In [24]:
# converting
import numpy as np
a = torch.ones(5)
print(a)
b = a.numpy()
print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>


In [25]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [26]:
a += 1
print(a)

[2. 2. 2. 2. 2.]


In [27]:
print(b)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
# moving between cpu and gpu
if torch.cuda.is_available():
  device = torch.device('cuda')
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x + y
  z = z.to('cpu')

In [29]:
# marking that tensor will optimize
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
